version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hercycle
      MYSQL_USER: admin
      MYSQL_PASSWORD: hercycle123
    ports:
      - "3306:3306"
    volumes:
      - mysql-db-data:/var/lib/mysql

  app:
    build: .
    container_name: hercycle-backend
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/hercycle?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: hercycle123
      JWT_SECRET: 9a62dc3625714e8c871d374d6c4d7e2e8f192b02e7b41e8c71a3d3c8c7f3e8b1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9
      JWT_EXPIRATION: 86400000
      JWT_REFRESH_EXPIRATION: 604800000

volumes:
  mysql-db-data:
