# Server Configuration
server.port=8080

# Database Configuration (AWS RDS MySQL)
spring.datasource.url=jdbc:mysql://hercycle.cczkqckgorra.us-east-1.rds.amazonaws.com:3306/hercycle?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=admin
spring.datasource.password=hercycle123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# HikariCP Connection Pool Settings
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=15
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.pool-name=HerCycleHikariPool

# JWT Security Configurations
hercycle.jwt.secret=9a64e12e2c8a149c4d9a44e59ef8a1c97a80b6df4b0f0a2e5a9c0c8a6bdf7e3a
# 24 Hours in Milliseconds
hercycle.jwt.expiration=86400000
# 7 Days in Milliseconds
hercycle.jwt.refreshExpiration=604800000

# OpenAPI Swagger Details
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui/index.html
springdoc.swagger-ui.operationsSorter=method

# File Upload Sizes
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
