# Database Configuration (AWS RDS MySQL for Dev)
spring.datasource.url=${DB_URL:jdbc:mysql://hercycle.cczkqckgorra.us-east-1.rds.amazonaws.com:3306/hercycle?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USERNAME:admin}
spring.datasource.password=${DB_PASSWORD:hercycle123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Configuration for Dev
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Security Configuration for Dev
hercycle.jwt.secret=${JWT_SECRET:9a64e12e2c8a149c4d9a44e59ef8a1c97a80b6df4b0f0a2e5a9c0c8a6bdf7e3a}

# Actuator Configuration for Dev
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
